nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  restart: always
  container_name: nginx
  ports:
    - "80:80"
  environment:
    - DEFAULT_HOST=ci.docker

jenkins-data:
  build: .
  container_name: jenkins-data
  volumes:
    - /var/jenkins_home
    
jenkins:
  image: jenkins
  container_name: jenkins
  restart: always
  ports:
    - "8080"
  environment:
    - VIRTUAL_HOST=ci.docker
    - VIRTUAL_PORT=8080
  volumes_from:
    - jenkins-data